export interface Branch {
  id: number,
  clientId: number,
  branchName: string,
  smallDetails: string,
  image: any,
  imagePath: string,
  details: string,
  addressLine1: string,
  addressLine2: string,
  googleMap: string,
  phone: string,
  email: string,
  masterId: number,
  languageInfoId: number,
  sortIndex: number,
  status: number,
  statusText: string,
  lastUpdated: string,
  lastUpdatedText: string,
  languageName: string,
  contactRequests: any,
  openingHours: any
}
