export interface HtmlContent {
  id: number,
  htmlId: number,
  contentType: number,
  contentTypeText: string,
  title: string,
  subTitle: string,
  smallDetails: string,
  bigText: string,
  image: any,
  imagePath: string,
  link: string,
  galleryId: number,
  sortIndex: number,
  status: number,
  lastUpdate: string,
  lastUpdateText: string,
  htmlTitle: string,
  statusText: string,
  galleryTitle: string,
}
